apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops
  labels:
    app: gitops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
      - name: gitops
        image: ulrichnoumsi/gitops:v1
        ports:
        - containerPort: 80
